Add purchase API
Gadzhieva/cinema-room-service pull request #1
Opened 2021-11-07 20:40 UTC by Gadzhieva

2021-11-07 21:11 UTC, GadzhievFarid requested changes

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/CustomExceptionHandler.java
> +    }
Why do we use ResponseStatusException if we are returning custom ExceptionDto anyway? I think throwing custom exceptions makes more sense

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/Main.java
> +import javax.swing.text.TabExpander;
This import is not used

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/Seat.java
> +        }
Magic numbers should be extracted to constants with self-descriptive names

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/Seat.java
> +    boolean available = true;
Fields should be private

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/SeatDto.java
> +    }
Would be nice to have all constructors near

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/TheaterService.java
> +        }
Minor: I think this is a bit more readable

```suggestion
        if (!seat.isAvailable()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "The ticket has been already purchased!");
            }

        seat.setAvailable(false);
        return new SeatDto(seat);
```

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/TheatreController.java
>  public class TheatreController {
Is it Theater or Theatre? We should decide and stick to one spelling

2021-11-07 21:11 UTC, GadzhievFarid commented on src/cinema/Seat.java
> +        }
`this` is used not uniformly, i.e. `this.column`, but just `price`

2021-11-08 17:39 UTC, Gadzhieva commented
Thank you, fixed

2021-11-08 17:46 UTC, GadzhievFarid approved these changes
Good job

2021-11-08 19:28 UTC, merged